services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      backend1:
        condition: service_healthy
      backend2:
        condition: service_healthy

  backend1:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./backend1.html:/usr/share/nginx/html/index.html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3

  backend2:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./backend2.html:/usr/share/nginx/html/index.html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3